### ISSUE TITLE
 ... must be of the type array, null given

### ISSUE THREAD

**Issue by trailsnail** [hitmeister/api-sdk-php#3]
Here is a stacktrace from an order I received, which contains "NULL" in property "claim".
Is it a problem with the order, or in class "AbstractTransfer.php"? How will it be fixed?
Thanks :)
```
Argument 2 passed to Hitmeister\Component\Api\Transfers\AbstractTransfer::makeTransfer() must be of the type array, null given, called in .../api-sdk/src/Transfers/AbstractTransfer.php on line 107 and defined
#0 /api-sdk/src/Transfers/AbstractTransfer.php(153): error_handler(4096, 'Argument 2 pass...', '/home/COMPLEX/m...', 153, Array)
#1 /api-sdk/src/Transfers/AbstractTransfer.php(107): Hitmeister\Component\Api\Transfers\AbstractTransfer::makeTransfer('Hitmeister\\Comp...', NULL)
#2 /api-sdk/src/Transfers/AbstractTransfer.php(159): Hitmeister\Component\Api\Transfers\AbstractTransfer->fromArray(Array)
#3 /api-sdk/src/Cursor.php(185): Hitmeister\Component\Api\Transfers\AbstractTransfer::makeTransfer('\\Hitmeister\\Com...', Array)
#4 /api-sdk/src/Cursor.php(85): Hitmeister\Component\Api\Cursor->getCurrent()
#5 /scripts/hitmeister.php(94): Hitmeister\Component\Api\Cursor->current()
#6 {main}
```
My Code:
```
$client = ClientBuilder::create()
                               ->setClientKey(HITMEISTER_CLIENT_KEY)
                               ->setClientSecret(HITMEISTER_SECRET_KEY)
                               ->build();

        $hitmeisterOrders = $client->orderUnits()->find(array("need_to_be_sent"), NULL, date("Y-m-d H:i:s",time()-48*3600));
```

**Comment by trailsnail** [comment]
This works great. Thanks ;)
